version: '3.8'

services:
  homework_bot:
    build: .
    container_name: homework_bot
    restart: always
    volumes:
      # ВАЖНО: Мы привязываем файл базы данных
      # Слева - файл на сервере, Справа - путь в контейнере
      - ./data.json:/app/data.json
    env_file:
      - .env