services:
  homework_bot:   # Имя может быть другим, не меняй его
    build: .
    container_name: homework_bot
    restart: always
    network_mode: host    # <--- ДОБАВЬ ВОТ ЭТУ МАГИЧЕСКУЮ СТРОЧКУ
    volumes:
      - ./data.json:/app/data.json
    env_file:
      - .env